export interface AnnouncementItem {
    id: number;
    title: string;
    desc: string;
    body: string[];
    date: string;
    month: string;
    year: string;
    category: string;
    urgent?: boolean;
    author: string;
    department: string;
    deadline?: string;
    tags: string[];
}

export const allAnnouncements: AnnouncementItem[] = [
    {
        id: 1,
        title: "2024-2025 tədris ili yaz semestri imtahan cədvəli açıqlandı",
        desc: "Bakalavr, magistr və doktorantura tələbələri üçün 2024-2025 tədris ilinin yaz semestri imtahanlarının cədvəli rəsmi olaraq açıqlanmışdır.",
        body: [
            "Azərbaycan Texniki Universitetinin Tədris İşləri üzrə Prorektorluğu 2024-2025 tədris ilinin yaz semestri imtahanlarının cədvəlini elan edir. İmtahanlar 2025-ci il yanvarın 20-dən fevralın 10-dək davam edəcəkdir.",
            "Bakalavr proqramlarının I, II, III və IV kurs tələbələri üçün imtahanlar müvafiq fakültə binalarında, magistr və doktorantura tələbələri üçün isə 1 nömrəli tədris korpusunda keçiriləcəkdir. İmtahan cədvəlini universitiyin rəsmi saytının Tədris bölməsindən yükləyə bilərsiniz.",
            "Hər bir tələbə imtahana əvvəlcədən müraciət etməli, tələbə şəxsiyyət vəsiqəsini yanında gətirməlidir. Gecikmə olmadan imtahan salonuna daxil olmaq üçün imtahanın başlanmasından ən azı 15 dəqiqə əvvəl binada olmaq tövsiyə olunur.",
            "İmtahanla bağlı suallar və ya əlavə məlumat üçün müvafiq fakültə dekanları ilə əlaqə saxlaya bilərsiniz. Cədvəldə son dəqiqə dəyişiklikləri baş verərsə, tələbələr e-poçt vasitəsilə məlumatlandırılacaqdır.",
        ],
        date: "15",
        month: "Yanvar",
        year: "2025",
        category: "Akademik",
        urgent: true,
        author: "Tədris İşləri üzrə Prorektorluq",
        department: "Tədris İşləri",
        deadline: "20 Yanvar 2025",
        tags: ["İmtahan", "Cədvəl", "Tədris", "Bakalavr", "Magistr"],
    },
    {
        id: 2,
        title: "Erasmus+ Tələbə Mübadiləsi Proqramı üçün müraciət başladı",
        desc: "2025-2026 tədris ili üçün Erasmus+ mübadiləsi proqramına müraciətlər qəbul edilir. Tələbələr 28 Fevral 2025-ci il tarixinə kimi müraciət edə bilərlər.",
        body: [
            "Azərbaycan Texniki Universitetinin Beynəlxalq Əlaqələr Şöbəsi 2025-2026 tədris ili üçün Erasmus+ tələbə mübadiləsi proqramına müraciətlərin qəbulunu elan edir. Bu il 12 Avropa universitetinə müraciət etmək imkanı mövcuddur.",
            "Proqram həm bakalavr (3-4-cü kurs), həm magistr, həm də doktorantura tələbələrini əhatə edir. Mübadilə müddəti bir semestrdir (5 ay) və tam maliyyə dəstəyi (seyahət, yaşayış, cib xərci) Erasmus+ tərəfindən ödənilir.",
            "Müraciət üçün tələb olunanlar: GPA ≥ 3.0, IELTS 5.5 / TOEFL 72 (və ya bəzi universitετlər üçün Alman/Fransız dili sertifikatı), motivasiya məktubu, 2 tövsiyə məktubu, tədris planı. Bütün sənədlər Beynəlxalq Əlaqələr Şöbəsinə şəxsən və ya erasmus@aztu.edu.az e-poçtu vasitəsilə təqdim edilə bilər.",
            "Seçilmiş tələbələrə martın 15-dən başlayaraq e-poçt vasitəsilə məlumat veriləcəkdir. Ətraflı məlumat üçün Beynəlxalq Əlaqələr Şöbəsini Bldg. 1, otaq 214-də ziyarət edin.",
        ],
        date: "10",
        month: "Yanvar",
        year: "2025",
        category: "Tədris",
        urgent: false,
        author: "Beynəlxalq Əlaqələr Şöbəsi",
        department: "Beynəlxalq Əlaqələr",
        deadline: "28 Fevral 2025",
        tags: ["Erasmus+", "Mübadilə", "Beynəlxalq", "Tələbə", "Stipendiya"],
    },
    {
        id: 3,
        title: "2025-2026 magistr proqramlarına qəbul elanı",
        desc: "AzTU 2025-2026 tədris ili üçün 18 ixtisas üzrə magistr proqramlarına qəbul elan edir. Son müraciət tarixi 31 mart 2025-ci ildir.",
        body: [
            "Azərbaycan Texniki Universiteti 2025-2026 tədris ili üçün magistr proqramlarına qəbul kampaniyasını rəsmi olaraq başlatdı. Bu il Mühəndislik, İnformasiya Texnologiyaları, Enerji, Ekoloji Mühəndislik və Texniki İqtisadiyyat sahələri üzrə 18 ixtisasda qəbul aparılacaq.",
            "Qəbul olunan namizədlərə müəyyən meyarlara uyğun olaraq tam və ya qismən dövlət təqaüdü verilə bilər. Əcnəbi vətəndaşlar da müraciət edə bilər — beynəlxalq namizədlər üçün xüsusi kvota nəzərdə tutulmuşdur.",
            "Müraciət etmək istəyənlər: bakalavriat diplomu (orta GPA ≥ 2.7), 2 tövsiyə məktubu, motivasiya məktubu, şəxsiyyət vəsiqəsinin surəti. Onlayn müraciət portalı admissions.aztu.edu.az saytında mövcuddur.",
            "Qəbul imtahanları (yazılı test + müsahibə) aprelin 10-20 tarixlərində keçiriləcəkdir. Nəticələr aprelin 30-dək elan ediləcəkdir.",
        ],
        date: "05",
        month: "Yanvar",
        year: "2025",
        category: "Qəbul",
        urgent: false,
        author: "Qəbul Komissiyası",
        department: "Qəbul və Tədris",
        deadline: "31 Mart 2025",
        tags: ["Qəbul", "Magistr", "2025", "İxtisas"],
    },
    {
        id: 4,
        title: "Tələbə elmi konfransı üçün abstrakt təqdimatı",
        desc: "AzTU-nun illik Tələbə Elmi Konfransı üçün məruzə abstrakt qəbulu başlayıb. Mövzu: 'Rəqəmsal Çevrilmə və Texniki Elmlər'.",
        body: [
            "Azərbaycan Texniki Universitetinin Elm Şöbəsi 2025-ci il aprel ayında keçiriləcək illik Tələbə Elmi Konfransı üçün abstrakt qəbulunu elan edir. Bu ilin konfransının mövzusu 'Rəqəmsal Çevrilmə və Texniki Elmlər'dir.",
            "Abstrakt tərtibi qaydaları: azərbaycan və ya ingilis dilində, maksimum 250 söz, 3-5 açar söz, müəllifin adı, fakültəsi, elmi rəhbəri. Abstrakt Microsoft Word formatında (.docx) conf2025@aztu.edu.az ünvanına göndərilməlidir.",
            "Qəbul olunan işlər şifahi məruzə (15 dəq) və ya poster (poster seksiyası) formatında təqdim edilə bilər. Ən yaxşı 3 iş ödülləndirilərək AzTU Elmi Jurnalında nəşr olunmaq üçün tövsiyə alacaq.",
            "Konfrans proqramı, qeydiyyat və ətraflı məlumat üçün sci.aztu.edu.az saytına daxil olun. Hər tələbə maksimum 2 işlə iştirak edə bilər.",
        ],
        date: "28",
        month: "Dekabr",
        year: "2024",
        category: "Tədbirlər",
        urgent: false,
        author: "Elm Şöbəsi",
        department: "Elmi Tədqiqatlar",
        deadline: "15 Fevral 2025",
        tags: ["Konfrans", "Elm", "Tələbə", "Məruzə", "Araşdırma"],
    },
    {
        id: 5,
        title: "Təqaüd proqramı üzrə maliyyə yardımı müraciəti",
        desc: "Sosial müdafiəyə ehtiyacı olan, yüksək akademik göstəricili tələbələr üçün 2025-ci il birinci yarımillik təqaüd müraciəti açıqdır.",
        body: [
            "AzTU Maliyyə Şöbəsi 2025-ci il birinci yarımilliyi üçün tələbə təqaüd proqramı üzrə müraciətlərin qəbulunu elan edir. Proqram sosial müdafiəyə ehtiyacı olan və yüksək akademik nailiyyət göstərən tələbələrə yönəlmişdir.",
            "Müraciət şərtləri: GPA ≥ 3.5, sosial ehtiyac sənədi (ailə gəliri aşağı hədd), əvvəlki semestrdə intizam pozuntusunun olmaması, tam günlük tədris (part-time xaric). Müraciət forması və tələb olunan sənədlər Maliyyə Şöbəsindən (Bldg. 2, otaq 108) alına bilər.",
            "Hər tələbəyə ayda 150 manat məbləğində 6 aylıq təqaüd verilir. Qiymətləndirmə komissiyası sənədlər əsasında seçim aparacaq və nəticələri yanvarın 25-ə qədər elan edəcəkdir.",
            "Suallarınız üçün Maliyyə Şöbəsi ilə iş saatlarında (09:00-17:00, bazar ertəsi-cümə) əlaqə saxlaya bilərsiniz: maliyye@aztu.edu.az.",
        ],
        date: "22",
        month: "Dekabr",
        year: "2024",
        category: "Maliyyə",
        urgent: false,
        author: "Maliyyə Şöbəsi",
        department: "Maliyyə",
        deadline: "20 Yanvar 2025",
        tags: ["Təqaüd", "Maliyyə", "Tələbə", "Sosial"],
    },
    {
        id: 6,
        title: "Kitabxana elektron resurslarına yeni abunəlik",
        desc: "AzTU Kitabxanası 2025-ci ildən Scopus, Web of Science və IEEE Xplore verilənlər bazalarına yeni abunəliklər əldə edib.",
        body: [
            "Azərbaycan Texniki Universitetinin Mərkəzi Kitabxanası 2025-ci il yanvar ayından etibarən Scopus, Web of Science (WoS) və IEEE Xplore beynəlxalq elmi verilənlər bazalarına tam abunəlik əldə etdiyini elan edir.",
            "Bu resurslara daxil olmaq üçün tələbə/müəllim hesabınızla universitetin daxili şəbəkəsinə (campus Wi-Fi və ya VPN) qoşulun. Kənardan daxil olmaq istəyənlər üçün AzTU VPN konfiqurasiyası haqqında məlumat it.aztu.edu.az saytında mövcuddur.",
            "Scopus: 7,000+ nəşriyyatın 25,000+ jurnalını əhatə edir. WoS: Nobel mükafatçılarının tədqiqatları daxil olmaqla 12,000+ jurnala çıxış. IEEE Xplore: 5 miliondan çox mühəndislik və texnologiya sənədi.",
            "Kitabxana saatlarda resurs istifadəsi üzrə pulsuz seminarlar təşkil edir. Qeydiyyat üçün lib.aztu.edu.az saytını ziyarət edin. İlk seminar 15 yanvar 2025-ci ildə keçiriləcəkdir.",
        ],
        date: "18",
        month: "Dekabr",
        year: "2024",
        category: "Akademik",
        urgent: false,
        author: "Mərkəzi Kitabxana",
        department: "Kitabxana Xidmətləri",
        tags: ["Kitabxana", "Elm", "Verilənlər Bazası", "Tədqiqat"],
    },
    {
        id: 7,
        title: "İnnovasiya Startap Müsabiqəsi — Müraciətlər açıqdır",
        desc: "AzTU Texnopark tərəfindən təşkil olunan illik startap müsabiqəsinin qaliblərindən ən yaxşısı 10,000 AZN münasibət fondu alacaq.",
        body: [
            "AzTU Texnopark 2025-ci ilin birinci rübündə keçiriləcək İllik İnnovasiya Startap Müsabiqəsinin müraciət prosedurasini elan edir. Müsabiqə gənc texnologiya sahibkarlarını maliyyə dəstəyi, mentorluq və inkubasiya xidmətləri ilə mükafatlandırır.",
            "Müsabiqəyə fərdi iştirakçılar və ya 2-5 nəfərlik komandalar iştirak edə bilər. İştirakçıların ən azı biri AzTU tələbəsi, magistrantı, doktorantı və ya xərrici olmalıdır. Layihə texnologiya, mühəndislik və ya dayanıqlı inkişaf sahəsinə aid olmalıdır.",
            "Mükafat fondu: 1-ci yer — 10,000 AZN + 6 aylıq AzTU Texnopark inkubasiyası; 2-ci yer — 5,000 AZN; 3-cü yer — 2,500 AZN. Bundan əlavə, seçilmiş layihələr investor görüşünə dəvət alacaq.",
            "Müraciət forması və layihə şərtləri texnopark.aztu.edu.az saytında mövcuddur. Son müraciət tarixi: 10 fevral 2025. Müsahibələr 20-25 fevral tarixlərində keçiriləcəkdir.",
        ],
        date: "15",
        month: "Dekabr",
        year: "2024",
        category: "Tədbirlər",
        urgent: false,
        author: "AzTU Texnopark",
        department: "İnnovasiya Mərkəzi",
        deadline: "10 Fevral 2025",
        tags: ["Startap", "İnnovasiya", "Texnopark", "Müsabiqə", "Biznes"],
    },
    {
        id: 8,
        title: "Tələbə yataqxana qeydiyyatı — Payız semestri",
        desc: "2024-2025 tədris ilinin payız semestri üçün yataqxana yerləri üzrə müraciətlər 10 yanvar 2025-ci il tarixindən qəbul edilir.",
        body: [
            "AzTU İnzibatiyyat Şöbəsi 2024-2025 tədris ilinin ikinci yarısı (payız semestri) üçün tələbə yataqxana yerlərinin yenilənməsi prosedurasini elan edir. Mövcud sakinlər qeydiyyatlarını yeniləməli, yeni müraciətçilər isə ərizə verməlidir.",
            "Yataqxana haqqı: 2 nəfərlik otaq — 80 AZN/ay, 3 nəfərlik otaq — 60 AZN/ay. Ödəniş Maliyyə Şöbəsi üzərindən bank köçürməsi ilə həyata keçirilir. Yanvarın 25-dən başlayaraq yataqxana vəsiqələri verilir.",
            "Müraciət üçün tələb olunanlar: tələbə biletinin surəti, şəxsiyyət vəsiqəsinin surəti, 2 ədəd foto, müraciət forması (İnzibatiyyat Şöbəsindən alınır). Sosial müdafiəyə ehtiyacı olan tələbələr üçün endirimlər mövcuddur.",
            "Yataqxana qaydaları ilə tanış olmaq üçün AzTU rəsmi saytının Tələbə Həyatı bölməsinə daxil olun. Suallarınız üçün: dormitory@aztu.edu.az.",
        ],
        date: "10",
        month: "Dekabr",
        year: "2024",
        category: "İnzibati",
        urgent: false,
        author: "İnzibatiyyat Şöbəsi",
        department: "Tələbə İşləri",
        deadline: "25 Yanvar 2025",
        tags: ["Yataqxana", "Tələbə", "Qeydiyyat", "Yaşayış"],
    },
    {
        id: 9,
        title: "Sertifikat proqramları — Paylanma üçün son gün",
        desc: "Python, Java, AutoCAD, BIM və Kibertəhlükəsizlik sahələri üzrə peşəkar sertifikat proqramlarına qeydiyyat başlayıb.",
        body: [
            "AzTU Əlavə Təhsil Mərkəzi 2025-ci il yanvar-iyun dövrü üçün bir neçə peşəkar sertifikat proqramını elan edir. Proqramlar həm tələbələrə, həm də sənaye mütəxəssislərinə yönəlmişdir.",
            "Mövcud proqramlar: Python ilə Məlumat Analizi (8 həftə), Java Proqramlaşdırması (10 həftə), AutoCAD 2D/3D (6 həftə), BIM Texnologiyaları (8 həftə), Kibertəhlükəsizlik Əsasları (10 həftə). Dərslər həftəlik 2 dəfə, axşam saatlarında keçirilir.",
            "Proqram haqqı: 200-350 AZN arasında dəyişir (proqrama görə). AzTU tələbələri üçün 30% endirim mövcuddur. Gruplar formalaşdıqda dərslərə başlanılır — minimum 10 iştirakçı tələb olunur.",
            "Qeydiyyat və ətraflı məlumat üçün: extra.aztu.edu.az. Ödənişsiz ilk dərslərə qatılmaq üçün müraciət yanvarın 20-dən başlayır.",
        ],
        date: "05",
        month: "Dekabr",
        year: "2024",
        category: "Tədris",
        urgent: false,
        author: "Əlavə Təhsil Mərkəzi",
        department: "Əlavə Təhsil",
        deadline: "20 Yanvar 2025",
        tags: ["Sertifikat", "Kurs", "Peşəkar İnkişaf", "Python", "Kibertəhlükəsizlik"],
    },
    {
        id: 10,
        title: "Tələbə kartlarının yenilənməsi — Məcburi proses",
        desc: "Bütün aktiv tələbələrin tələbə ID kartlarını yanvarın 31-dək yeniləməsi tələb olunur. Yenilənməmiş kartlar fevraldan etibarsız sayılacaq.",
        body: [
            "AzTU İnzibatiyyat Şöbəsi bütün aktiv tələbələrin tələbə ID kartlarını 31 yanvar 2025-ci il tarixinə qədər yeniləməsini tələb edir. Bu proses hər il keçirilir və tədris ili üçün tələbə statusunu rəsmiləşdirir.",
            "Kart yeniləmə proseduru: 1) Maliyyə Şöbəsindən borcun olmadığına dair arayış alın; 2) Dekanatlıqdan mövcud semestrdə qeydiyyatın olduğunu təsdiq edin; 3) Sənədlər (şəxsiyyət vəsiqəsi, tələbə qeydiyyat çıxarışı, 1 ədəd foto) ilə İnzibatiyyat Şöbəsinə (Bldg. 1, otaq 101) müraciət edin.",
            "Yenilənməmiş kartlar 1 fevral 2025-ci ildən etibarən kampus giriş sistemlərindən, kitabxanadan, idman zallarından və digər tələbə xidmətlərindən istifadə üçün etibarsız sayılacaqdır.",
            "Kart yeniləmə saatları: Bazar ertəsi — Cümə, 09:00-17:00 (nahar fasiləsi: 13:00-14:00). Suallarınız üçün: registrar@aztu.edu.az.",
        ],
        date: "02",
        month: "Dekabr",
        year: "2024",
        category: "İnzibati",
        urgent: true,
        author: "İnzibatiyyat Şöbəsi",
        department: "Tələbə İşləri",
        deadline: "31 Yanvar 2025",
        tags: ["ID Kart", "Qeydiyyat", "İnzibati", "Tələbə"],
    },
];

export const announcementCategories = [
    "Hamısı",
    "Akademik",
    "Tədris",
    "Qəbul",
    "Maliyyə",
    "Tədbirlər",
    "İnzibati",
];

export const announcementCategoryColors: Record<string, string> = {
    Akademik: "bg-[#1a2355]",
    Tədris: "bg-emerald-500",
    Qəbul: "bg-[#ee7c7e]",
    Maliyyə: "bg-amber-500",
    Tədbirlər: "bg-violet-500",
    İnzibati: "bg-slate-500",
};
